version: '3'

services:
  mysql:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ../mysql/init:/docker-entrypoint-initdb.d
      - ../mysql/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
